# -*- coding: utf-8 -*-
"""COVID19_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UbawjMjNz0v-C_0O9ZHhZGScoQpWCbgp
"""

# ================================================================
# COVID-19 Data Analysis Project
# Dataset: https://covid.ourworldindata.org/data/owid-covid-data.csv
# ================================================================
# BEFORE RUNNING:
#   1. Download the dataset from the link above
#   2. Save it as "owid-covid-data.csv" in the same folder as this file
#   3. Open terminal and run:  pip install pandas matplotlib seaborn plotly
#   4. Then run:               python covid_analysis.py
# ================================================================


# --- Import libraries ---
# pandas  -> works like Excel in Python (rows, columns, filters)
# matplotlib and seaborn -> draw charts
# plotly  -> draw interactive world map

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px


# ================================================================
# STEP 1: LOAD THE DATA
# ================================================================

import kagglehub
import os

# Download the dataset automatically from Kaggle
path = kagglehub.dataset_download("caesarmario/our-world-in-data-covid19-dataset")
print("Dataset downloaded to:", path)

# Find the CSV file inside the downloaded folder
csv_file = os.path.join(path, "owid-covid-data.csv")

# Load it
df = pd.read_csv(csv_file)


# ================================================================
# STEP 2: LOOK AT THE DATA
# ================================================================

# See the first 5 rows
print("\nFirst 5 rows:")
print(df.head())

# See all column names
print("\nColumn names:")
print(df.columns.tolist())


# ================================================================
# STEP 3: KEEP ONLY THE COLUMNS WE NEED
# ================================================================

# We do not need all 67 columns
# We only pick these important ones

df = df[[
    "location",            # country name
    "continent",           # which continent (Asia, Europe, etc.)
    "date",                # date of the record
    "total_cases",         # total cases up to this date
    "new_cases",           # new cases on this date
    "total_deaths",        # total deaths up to this date
    "new_deaths",          # new deaths on this date
    "total_vaccinations",  # total vaccine doses given
    "population"           # population of the country
]]

print("\nWe kept these columns:")
print(df.columns.tolist())


# ================================================================
# STEP 4: CLEAN THE DATA
# ================================================================

# --- Fix the date column ---
# Right now "date" is text like "2020-03-15"
# We convert it to a real date so Python understands it
df["date"] = pd.to_datetime(df["date"])

# --- Remove non-country rows ---
# The dataset has rows like "World", "Asia", "Europe"
# These are group totals, not real countries
# They have no continent value, so we remove them
df = df[df["continent"].notna()]

# --- Fill empty number cells with 0 ---
# Some cells are empty (NaN) because data was not reported that day
# We fill them with 0 so we can do math without errors
df["total_cases"]        = df["total_cases"].fillna(0)
df["total_deaths"]       = df["total_deaths"].fillna(0)
df["new_cases"]          = df["new_cases"].fillna(0)
df["new_deaths"]         = df["new_deaths"].fillna(0)
df["total_vaccinations"] = df["total_vaccinations"].fillna(0)
df["population"]         = df["population"].fillna(1)  # avoid dividing by zero

print("\nCleaning done!")
print("Rows remaining:", len(df))


# ================================================================
# STEP 5: ADD NEW COLUMNS
# ================================================================

# --- Death Rate ---
# Death rate = (total deaths / total cases) x 100
# Example: 200 deaths out of 10,000 cases = 2% death rate
# We use .replace(0, 1) to avoid divide-by-zero error

df["death_rate"] = (df["total_deaths"] / df["total_cases"].replace(0, 1)) * 100

# --- Cases Per Million ---
# This is used to compare countries fairly
# A country of 10 million with 1 million cases is more affected
# than a country of 1 billion with the same 1 million cases

df["cases_per_million"] = (df["total_cases"] / df["population"]) * 1000000

print("\nNew columns added: death_rate, cases_per_million")


# ================================================================
# STEP 6: GET LATEST DATA FOR EACH COUNTRY
# ================================================================

# The dataset has one row per day per country
# We want only the most recent (latest) row for each country

# First sort all rows by date (oldest to newest)
df = df.sort_values("date")

# Then for each country, keep only the last row
latest = df.groupby("location").last().reset_index()

print("\nNumber of countries:", len(latest))


# ================================================================
# STEP 7: FIND TOP 10 COUNTRIES BY TOTAL CASES
# ================================================================

# Sort countries by total cases, biggest first
# Then take the top 10
top10 = latest.sort_values("total_cases", ascending=False).head(10)

print("\nTop 10 Countries by Total Cases:")
print(top10[["location", "total_cases", "total_deaths", "death_rate"]])


# ================================================================
# STEP 8: CHART 1 — BAR CHART: TOP 10 COUNTRIES BY TOTAL CASES
# ================================================================

plt.figure(figsize=(12, 6))

# Draw the bar chart
# We divide total_cases by 1 million so the numbers are not too big
plt.bar(
    top10["location"],
    top10["total_cases"] / 1000000,
    color="tomato"
)

# Add labels and title
plt.title("Top 10 Countries by Total COVID-19 Cases", fontsize=15)
plt.xlabel("Country")
plt.ylabel("Total Cases (in Millions)")
plt.xticks(rotation=40, ha="right")  # tilt country names so they fit

plt.tight_layout()
plt.savefig("chart1_top10_cases.png")  # save the chart as an image
plt.show()

print("\nChart 1 saved: chart1_top10_cases.png")


# ================================================================
# STEP 9: CHART 2 — BAR CHART: TOP 10 COUNTRIES BY DEATH RATE
# ================================================================

# Only include countries with more than 10,000 cases
# A country with 2 cases and 1 death = 50% death rate, which is misleading
filtered = latest[latest["total_cases"] > 10000]
top10_dr = filtered.sort_values("death_rate", ascending=False).head(10)

plt.figure(figsize=(12, 6))

plt.bar(
    top10_dr["location"],
    top10_dr["death_rate"],
    color="darkorange"
)

plt.title("Top 10 Countries by COVID-19 Death Rate", fontsize=15)
plt.xlabel("Country")
plt.ylabel("Death Rate (%)")
plt.xticks(rotation=40, ha="right")

plt.tight_layout()
plt.savefig("chart2_death_rate.png")
plt.show()

print("Chart 2 saved: chart2_death_rate.png")


# ================================================================
# STEP 10: CHART 3 — PIE CHART: CASES BY CONTINENT
# ================================================================

# Add up total cases for each continent
continent_data = latest.groupby("continent")["total_cases"].sum()

plt.figure(figsize=(8, 8))

plt.pie(
    continent_data,
    labels=continent_data.index,  # continent names as labels
    autopct="%1.1f%%",            # show percentage on each slice
    startangle=140
)

plt.title("COVID-19 Cases by Continent", fontsize=15)

plt.tight_layout()
plt.savefig("chart3_continent_pie.png")
plt.show()

print("Chart 3 saved: chart3_continent_pie.png")


# ================================================================
# STEP 11: CHART 4 — LINE CHART: DAILY NEW CASES OVER TIME
# ================================================================

# We will plot daily new cases for the top 5 countries
top5_countries = top10["location"].head(5).tolist()

# Keep only rows from those 5 countries
df_top5 = df[df["location"].isin(top5_countries)].copy()

# 7-day rolling average:
# Instead of using today's number, we take the average of the last 7 days
# This makes the line smooth instead of very spiky
df_top5["smooth_cases"] = df_top5.groupby("location")["new_cases"].transform(
    lambda x: x.rolling(7).mean()
)

plt.figure(figsize=(14, 7))

# Draw one line for each country
for country in top5_countries:
    one_country = df_top5[df_top5["location"] == country]
    plt.plot(
        one_country["date"],
        one_country["smooth_cases"] / 1000,  # show in thousands
        label=country,
        linewidth=2
    )

plt.title("Daily New COVID-19 Cases Over Time — Top 5 Countries", fontsize=14)
plt.xlabel("Date")
plt.ylabel("New Cases (Thousands, 7-day average)")
plt.legend()

plt.tight_layout()
plt.savefig("chart4_time_series.png")
plt.show()

print("Chart 4 saved: chart4_time_series.png")


# ================================================================
# STEP 12: CHART 5 — WORLD MAP (Interactive)
# ================================================================

# This creates an interactive HTML map
# You can hover over any country to see its numbers

fig = px.choropleth(
    latest,
    locations="location",
    locationmode="country names",
    color="total_cases",
    hover_name="location",
    color_continuous_scale="YlOrRd",   # yellow to red color scale
    title="COVID-19 Total Cases by Country"
)

fig.write_html("chart5_world_map.html")  # save as HTML file
fig.show()                               # open in browser

print("Chart 5 saved: chart5_world_map.html")


# ================================================================
# STEP 13: PRINT SUMMARY NUMBERS
# ================================================================

total_cases  = latest["total_cases"].sum()
total_deaths = latest["total_deaths"].sum()
global_dr    = (total_deaths / total_cases) * 100
total_vacc   = latest["total_vaccinations"].sum()

# Country with the most cases
worst_country = latest.sort_values("total_cases", ascending=False).iloc[0]

# Country with the highest death rate (min 10,000 cases)
worst_dr = filtered.sort_values("death_rate", ascending=False).iloc[0]

print("\n" + "=" * 45)
print("       GLOBAL COVID-19 SUMMARY")
print("=" * 45)
print(f"Total Cases Worldwide    : {total_cases:,.0f}")
print(f"Total Deaths Worldwide   : {total_deaths:,.0f}")
print(f"Global Death Rate        : {global_dr:.2f}%")
print(f"Total Vaccine Doses Given: {total_vacc:,.0f}")
print("-" * 45)
print(f"Most Cases     : {worst_country['location']} ({worst_country['total_cases']:,.0f})")
print(f"Highest Death Rate: {worst_dr['location']} ({worst_dr['death_rate']:.2f}%)")
print("=" * 45)
print("\nAll done! Check this folder for your 5 chart files.")